home/urls.py
from django.urls import path
from .views import index, contactus, aboutus, search, search_auto, faq

urlpatterns = [
    path("", index, name='index'),
    path("contact-us/", contactus, name='contact-us'),
    path("about-us/", aboutus, name='about-us'),
    path("search/", search, name='search'),
    path("search_auto/", search_auto, name='search-auto'),
    path("faq/", faq, name='search-faq'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

from home.views import category_products, product_detail
from order.views import shopcart
from user.views import login_form, signup_form, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('product/', include("product.urls")),
    path('order/', include("order.urls")),
    path('user/', include("user.urls")),
    path("category/<int:id>/<slug:slug>/", category_products, name='category-products'),
    path("product/<int:id>/<slug:slug>/", product_detail, name='product-detail'),
    path("shopcart/", shopcart, name='shopcart'),

    path("login/", login_form, name='login'),
    path("logout/", logout_view, name='logout'),
    path("signup/", signup_form, name='signup'),
]

from django.conf import  settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from .views import index, addtoshopcart, deletefromcart, orderproduct

urlpatterns = [
    path("", index, name='order-index'),
    path("addtoshopcart/<int:id>/", addtoshopcart, name='addtoshopcart'),
    path("deletefromcart/<int:id>/", deletefromcart, name='deletefromcart'),
    path("orderproduct/", orderproduct, name='orderproduct'),
]

order/models.py
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from product.models import Product


class ShopCart(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    quantity = models.IntegerField()

    def __str__(self):
        return str(self.product)

    @property
    def price(self):
        return (self.product.price)

    @property
    def amount(self):
        return (self.quantity * self.product.price)


class Order(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Preaparing', 'Preaparing'),
        ('OnShipping', 'OnShipping'),
        ('Completed', 'Completed'),
        ('Canceled', 'Canceled'),
    )
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    code = models.CharField(max_length=5, editable=False)
    first_name = models.CharField(max_length=10, )
    last_name = models.CharField(max_length=10, )
    phone = models.CharField(blank=True, max_length=20, )
    address = models.CharField(blank=True, max_length=150, )
    city = models.CharField(blank=True, max_length=20, )
    country = models.CharField(blank=True, max_length=20, )
    total = models.FloatField()
    status = models.CharField(choices=STATUS, max_length=10, default='New')
    ip = models.CharField(blank=True, max_length=20, )
    adminnote = models.CharField(blank=True, max_length=100, )
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.first_name

class OrderProduct(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Accepted', 'Accepted'),
        ('Canceled', 'Canceled'),
    )
    order = models.ForeignKey(Order, on_delete=models.CASCADE )
    user = models.ForeignKey(User, on_delete=models.CASCADE )
    product = models.ForeignKey(Product, on_delete=models.CASCADE )
    quantity = models.IntegerField()
    price = models.FloatField()
    amount = models.FloatField()
    status = models.CharField(choices=STATUS, max_length=10, default='New')
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.title

order/forms.py
from django import forms
from order.models import ShopCart, Order


class ShopCartForm(forms.ModelForm):
    class Meta:
        model = ShopCart
        fields = ['quantity',]

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name','last_name','address','phone','city','country']

order/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.utils.crypto import get_random_string

from product.models import Category, Product
from user.models import UserProfile
from .models import ShopCart, OrderProduct, Order
from .forms import ShopCartForm, OrderForm


# Create your views here.
def index(request):
    return HttpResponse("Order Page")

@login_required(login_url='/login')  # check login
def addtoshopcart(request, id):
    url = request.META.get('HTTP_REFERER')  # get last url
    current_user = request.user  # Accessing user session information

    # return HttpResponse(url)
    checkproduct = ShopCart.objects.filter(product_id=id)  # check product in shopcart
    if checkproduct:
        control = 1  # The product is in the cart
    else:
        control = 0  # The product is not in the cart

    if request.method == 'POST':  # if there is a post
        form = ShopCartForm(request.POST)
        print(form)
        print("form object created!")
        if form.is_valid():
            print("form is valid!")
            if control == 1: # Update shopcart
                data = ShopCart.objects.get(product_id=id)
                data.quantity += form.cleaned_data['quantity']
                data.save()  # save data
            else:  # Insert to ShopCart
                data = ShopCart()
                data.user_id = current_user.id
                data.product_id = id
                data.quantity = form.cleaned_data['quantity']
                data.save()
        messages.success(request, "Product added to Shopcart!.")
        return HttpResponseRedirect(url)

    else : # if there is no post
        if control == 1:  # Update shopcart
            data = ShopCart.objects.get(product_id=id)
            data.quantity += 1
            data.save()
        else:  # insert to ShopCart
            data = ShopCart()
            data.user_id = current_user.id
            data.product_id = id
            data.quantity = 1
            data.save()
        messages.success(request, "Product added to Shopcart.")
        return HttpResponseRedirect(url)

def shopcart(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity

    context = {
        'category':category,
        'shopcart':shopcart,
        'total':total,
        }
    return render(request, 'shopcart_products.html', context)

@login_required(login_url='/login')  # check login
def deletefromcart(request, id):
    ShopCart.objects.filter(id=id).delete()
    messages.success(request, "Your item deleted from the cart.")
    return HttpResponseRedirect('/shopcart')

def orderproduct(request):
    category = Category.objects.all()
    current_user = request.user
    shopcart = ShopCart.objects.filter(user_id=current_user.id)
    profile = UserProfile.objects.get(user_id=current_user.id)
    total = 0
    for rs in shopcart:
        total += rs.product.price * rs.quantity

    if request.method == "POST":
        form = OrderForm(request.POST)
        print("form is created!")
        #return HttpRespionse(request.POST.items())
        if form.is_valid():
            print("form is Valid!")
            # Send Credit Card to bank and get result if bank Response ok continue, if not, Show the error
            # ---------------------
            data = Order()
            data.first_name = form.cleaned_data['first_name']
            data.last_name = form.cleaned_data['last_name']
            data.address = form.cleaned_data['address']
            data.city = form.cleaned_data['city']
            data.phone = form.cleaned_data['phone']
            data.user_id = current_user.id
            data.total = total
            data.ip = request.META.get("REMOTE_ADDR")
            ordercode = get_random_string(5).upper() # Random cod
            data.code = ordercode
            data.save()

            # Move Shopcart items to Order Products items
            shopcart = ShopCart.objects.filter(user_id=current_user.id)
            for rs in shopcart:
                detail = OrderProduct()
                detail.order_id = data.id   # Order Id
                detail.product_id = rs.product_id
                detail.user_id = rs.user_id
                detail.quantity = rs.quantity
                detail.price = rs.product.price
                detail.amount = rs.amount
                detail.save()
                #   *** Reduce quantity of sold product from Amount of Product
                product = Product.objects.get(id=rs.product_id)
                product.amount -= rs.quantity
                product.save()
                # ***********************

            ShopCart.objects.filter(user_id=current_user.id).delete()   # Clear & Delete Shopcart
            request.session['cart_items'] = 0
            messages.success(request, "Your Order has been completed. Thank you")
            return render(request, "order_completed.html", {'ordercode':ordercode, 'category':category})
        else:
            messages.warning(request, form.errors)
            return HttpResponseRedirect("/order/orderproduct")

    form = OrderForm()
    context = {
        'category': category,
        'shopcart': shopcart,
        'profile': profile,
        'total': total,
        }
    return render(request, 'order_form.html', context)

order/templates/order_completed.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Order Completed {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active">Order Completed</li>
        </ul>
    </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">


            <div class="col-md-12">
                <div class="order-summary clearfix">
                    <div class="section-title">
                        <h3 class="title">Order Completed</h3>
                    </div>
                    <hr>
                    <h3>Dear {{ user.first_name }} {{ user.last_name }}</h3>
                    <hr>
                    <h4>Your order is completed</h4>
                    <h4>Order Code : {{ ordercode }} </h4>
                    <h4>Thank You</h4>
                    <hr>

                </div>
            </div>

        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->

{% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}

order/templates/order_form.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Order Page {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active"> Order Page</li>
        </ul>
    </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <form action="" method="POST">
                {% csrf_token %}
                <div class="col-md-6">
                    <div class="billing-details">

                        <div class="section-title">
                            <h4 class="title">Shipping Details</h4>
                        </div>
                        <p><label for="id_first_name">First Name : </label>
                            <input class="input" type="text" name="first_name" value="{{user.first_name}}"
                                   maxlength="10" required id="id_first_name">
                        </p>
                        <p><label for="id_last_name">Last Name : </label>
                            <input class="input" type="text" name="last_name" value="{{user.last_name}}" maxlength="10"
                                   required id="id_last_name">
                        </p>
                        <p><label for="id_address">Address : </label>
                            <input class="input" type="text" name="address" value="{{profile.address}}" maxlength="150"
                                   required id="id_address">
                        </p>
                        <p><label for="id_phone">Phone : </label>
                            <input class="input" type="text" name="phone" value="{{profile.phone}}" maxlength="20"
                                   required
                                   id="id_phone">
                        </p>
                        <p><label for="id_city">City : </label>
                            <select class="input" type="text" name="city" id="id_city">
                                <option value="{{profile.city}}" selected>{{ profile.city }}</option>
                                <option value="Istanbul"> Istanbul</option>
                                <option value="Ankara"> Ankara</option>
                                <option value="Izmir"> Izmir</option>
                                <option value="Bursa"> Bursa</option>
                                <option value="Konya"> Konya</option>
                                <option value="Yozgat"> Yozgat</option>
                            </select></p>
                        <p><label for="id_country">Country : </label>
                            <input class="input" type="text" name="country" value="{{profile.country}}" id="id_country">
                        </p>

                        <div class="pull-right">
                            <button type="submit" class="primary-btn"> Complete Order</button>
                        </div>

                    </div>
                </div>

                <div class="col-md-6">
                    <div class="shipping-methods">
                        <div class="section-title">
                            <h4 class="title">Payment Information</h4>
                        </div>
                        <p><label for="id_first_name">Total : </label>
                            <input class="input" type="text" name="total" readonly value="${{ total }}">
                        </p>
                        <p><label for="id_first_name">Credit Card Holder </label>
                            <input class="input" type="text" name="holder" value="">
                        </p>
                        <p><label for="id_first_name">Credit Card Number </label>
                            <input class="input" type="text" name="number" value="">
                        </p>
                        <p><label for="id_first_name">Credit Exp Date/Year </label>
                            <input class="input" type="text" name="ecpdate" value="">
                        </p>
                        <p><label for="id_first_name">Security Number </label>
                            <input class="input" type="text" name="secnumber" value="">
                        </p>
                    </div>
                </div>
            </form>

            <div class="col-md-12">
                <div class="order-summary clearfix">
                    <div class="section-title">
                        <h3 class="title">Shopcart Product Liist</h3>
                    </div>
                    <table class="shopping-cart-table table">
                        <thead>
                        <tr>
                            <th>Product</th>
                            <th></th>
                            <th class="text-center">Price</th>
                            <th class="text-center">Quantity</th>
                            <th class="text-center">Total</th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for rs in shopcart %}
                        <tr>
                            <td class="thumb"><img src="{{ rs.product.image.url }}" alt=""></td>
                            <td class="details">
                                <a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}/">
                                    {{ rs.product }}</a>
                            </td>
                            <td class="price text-center"><strong>${{ rs.product.price }}</strong></td>
                            <td class="qty text-center"><strong>${{ rs.quantity }}</strong></td>
                            <td class="total text-center"><strong class="primary-color">${{ rs.amount }}</strong></td>
                        </tr>
                        {% endfor %}

                        </tbody>
                        <tfoot>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>SUBTOTAL</th>
                            <th colspan="2" class="sub-total">${{ total }}</th>
                        </tr>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>SHIPING</th>
                            <td colspan="2">Free Shipping</td>
                        </tr>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>TOTAL</th>
                            <th colspan="2" class="total">${{ total }}</th>
                        </tr>
                        </tfoot>
                    </table>
                </div>

            </div>

        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /section -->

{% endblock %}
{% block foot %} {% include 'footer.html' %} {% endblock %}

order/templates/shopcart_products.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Shop Cart {% endblock %}
{% block keywords %} {{ setting.keywords }} {% endblock %}
{% block description %} {{ setting.description }} {% endblock %}

{% block sidebar %} {% include 'sidebar.html' %} {% endblock %}

{% block body %}

<!-- BREADCRUMB -->
<div id="breadcrumb">
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="#">Home</a></li>
            <li class="active"> Shopcart</li>
        </ul>
    </div>
</div>
<!-- /BREADCRUMB -->

<!-- section -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">


            <div class="col-md-12">
                <div class="order-summary clearfix">
                    <div class="section-title">
                        <h3 class="title">Shopcart Product List</h3>
                    </div>
                    <table class="shopping-cart-table table">
                        <thead>
                        <tr>
                            <th>Product</th>
                            <th></th>
                            <th class="text-center">Price</th>
                            <th class="text-center">Quantity</th>
                            <th class="text-center">Total</th>
                            <th class="text-right"></th>
                        </tr>
                        </thead>
                        <tbody>

                        {% for rs in shopcart %}
                        <tr>
                            <td class="thumb"><img src="{{ rs.product.image.url }}" alt=""></td>
                            <td class="details"><a href="/product/{{ rs.product.id }}/{{ rs.product.slug }}/">{{ rs.product }}</a></td>
                            <td class="price text-center"><strong>${{ rs.product.price }}</strong></td>
                            <td class="qty text-center"><strong>${{ rs.quantity }}</strong></td>
                            <td class="total text-center"><strong class="primary-color">${{ rs.amount }}</strong></td>
                            <td class="text-right"><a href="/order/deletefromcart/{{ rs.id }}/" onclick="return confirm('Delete ! Are you sure?')" class="main-btn icon-btn"><i class="fa fa-close"></i></a></td>
                        </tr>
                        {% endfor %}

                        </tbody>
                        <tfoot>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>SUBTOTAL</th>
                            <th colspan="2" class="sub-total">${{ total }}</th>
                        </tr>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>SHIPING</th>
                            <td colspan="2">Free Shipping</td>
                        </tr>
                        <tr>
                            <th class="empty" colspan="3"></th>
                            <th>TOTAL</th>
                            <th colspan="2" class="total">${{ total }}</th>
                        </tr>
                        </tfoot>
                    </table>
                    <div class="pull-right">
                        <a href="/order/orderproduct" class="primary-btn">Place Order</a>
                    </div>
                </div>

            </div>
            <!-- /row -->
        </div>
        <!-- /container -->
    </div>
    <!-- /section -->

    {% endblock %}
    {% block foot %} {% include 'footer.html' %} {% endblock %}